### ISSUE TITLE
Documentation updates for dealing with files nested in subfolders

### ISSUE THREAD

**Issue by jchristn** [SonnyX/NFS-Client#2]
Hi @SonnyX thanks again for putting together this wonderful library.  It took some digging, but I figured out how to use this library to be able to enumerate and deal with files in nested folders.  The documentation and examples weren't super clear, so I'm pasting them here in hopes that this saves someone else some headache in the future, and, that you'll consider updating the documentation to include them.

For context, I set up an Ubuntu 22.04 machine and created a share called `/share` with the following file and folder structure:
```
        /
        |-- root.txt
        |-- dir1
            |-- 1.txt
            |-- dir2
                |-- 2.txt
                |-- dir3
                    |-- 3.txt
```

I then modified `/etc/exports` to include it:
```
/share/ *(rw,sync,subtree_check,anonuid=0,anongid=0)
```

And exported it using `exportfs -a`.

Then, I created a new console project and referenced your library.  The code below connects, mounts, enumerates each directory, reads each file, all in succession.  The missing link for me was `client.Combine` and figuring out which slash to use (`\` or `/`) and how to handle nested folders.

And voila, it worked.
```
namespace Test.Nfs
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Net;
    using System.Text;
    using NFSLibrary;
    using NFSLibrary.Protocols.Commons;

    public static class Program
    {
        private static string _Hostname = "192.168.226.132";
        private static NfsClient.NfsVersion _Version = NfsClient.NfsVersion.V3;
        private static string _Share = "/share";

        /*

        /
        |-- root.txt
        |-- dir1
            |-- 1.txt
            |-- dir2
                |-- 2.txt
                |-- dir3
                    |-- 3.txt
                  
         */

        public static void Main(string[] args)
        {
            NfsClient client = null;
            Stream stream = null;
            string file = "";
            string folder = "";

            try
            {
                #region Initialize-and-Mount

                Console.WriteLine("");
                Console.WriteLine("Initializing client");
                client = new NfsClient(_Version);
                client.Connect(IPAddress.Parse(_Hostname));
                Console.WriteLine("Mounting device");
                client.MountDevice(_Share);

                #endregion

                #region List-Shares

                Console.WriteLine("");
                Console.WriteLine("Listing shares");
                List<string> exports = client.GetExportedDevices();
                if (exports != null && exports.Count > 0)
                    foreach (var share in exports)
                        Console.WriteLine("| " + share);

                #endregion

                #region Enumerate-Root

                Console.WriteLine("");
                Console.WriteLine("Listing root directory");
                foreach (string item in client.GetItemList("."))
                {
                    NFSAttributes attrib = client.GetItemAttributes(item);
                    if (attrib == null) continue;

                    bool isDirectory = client.IsDirectory(item);
                    Console.WriteLine("| " + item + " " + (isDirectory ? "(dir)" : null) + " " + attrib.Size + " bytes");
                }

                #endregion

                #region Read /root.txt

                Console.WriteLine("");
                file = client.Combine("root.txt", null);
                Console.WriteLine("Reading file root.txt: " + file);
                stream = new MemoryStream();
                client.Read("root.txt", ref stream);
                if (stream != null)
                {
                    stream.Seek(0, SeekOrigin.Begin);

                    int read = 0;
                    byte[] buf = new byte[4096];

                    while (true)
                    {
                        read = stream.Read(buf, 0, buf.Length);
                        if (read > 0)
                        {
                            byte[] segment = new byte[read];
                            Buffer.BlockCopy(buf, 0, segment, 0, read);
                            Console.WriteLine(Encoding.UTF8.GetString(segment));
                        }
                        else
                        {
                            break;
                        }
                    }
                }

                #endregion

                #region Enumerate /dir1

                Console.WriteLine("");
                folder = client.Combine("dir1", ".");
                Console.WriteLine("Listing dir1 directory: " + folder);
                foreach (string item in client.GetItemList(folder))
                {
                    NFSAttributes attrib = client.GetItemAttributes(client.Combine(item, "dir1"));
                    if (attrib == null) continue;

                    bool isDirectory = client.IsDirectory(client.Combine(item, "dir1"));
                    Console.WriteLine("| " + item + " " + (isDirectory ? "(dir)" : null) + " " + attrib.Size + " bytes");
                }

                #endregion

                #region Read /root.txt

                Console.WriteLine("");
                file = client.Combine("1.txt", "dir1");
                Console.WriteLine("Reading file 1.txt: " + file);
                stream = new MemoryStream();
                client.Read(file, ref stream);
                if (stream != null)
                {
                    stream.Seek(0, SeekOrigin.Begin);

                    int read = 0;
                    byte[] buf = new byte[4096];

                    while (true)
                    {
                        read = stream.Read(buf, 0, buf.Length);
                        if (read > 0)
                        {
                            byte[] segment = new byte[read];
                            Buffer.BlockCopy(buf, 0, segment, 0, read);
                            Console.WriteLine(Encoding.UTF8.GetString(segment));
                        }
                        else
                        {
                            break;
                        }
                    }
                }

                #endregion

                #region Enumerate /dir2

                Console.WriteLine("");
                folder = client.Combine("dir2", "dir1");
                Console.WriteLine("Listing dir2 directory: " + folder);
                foreach (string item in client.GetItemList(folder))
                {
                    Console.WriteLine("Processing item " + item);
                    NFSAttributes attrib = client.GetItemAttributes(client.Combine(item, "dir1"));
                    if (attrib == null) continue;

                    bool isDirectory = client.IsDirectory(client.Combine(item, "dir1"));
                    Console.WriteLine("| " + item + " " + (isDirectory ? "(dir)" : null) + " " + attrib.Size + " bytes");
                }

                #endregion

                #region Read /dir1/dir2/2.txt

                Console.WriteLine("");
                file = client.Combine("2.txt", "dir1\\dir2");
                Console.WriteLine("Reading file 2.txt: " + file);
                stream = new MemoryStream();
                client.Read(file, ref stream);
                if (stream != null)
                {
                    stream.Seek(0, SeekOrigin.Begin);

                    int read = 0;
                    byte[] buf = new byte[4096];

                    while (true)
                    {
                        read = stream.Read(buf, 0, buf.Length);
                        if (read > 0)
                        {
                            byte[] segment = new byte[read];
                            Buffer.BlockCopy(buf, 0, segment, 0, read);
                            Console.WriteLine(Encoding.UTF8.GetString(segment));
                        }
                        else
                        {
                            break;
                        }
                    }
                }

                #endregion

                #region Enumerate /dir3

                Console.WriteLine("");
                folder = client.Combine("dir3", "dir1\\dir2");
                Console.WriteLine("Listing dir3 directory: " + folder);
                foreach (string item in client.GetItemList(folder))
                {
                    Console.WriteLine("Processing item " + item);
                    NFSAttributes attrib = client.GetItemAttributes(folder);
                    if (attrib == null) continue;

                    bool isDirectory = client.IsDirectory(client.Combine(item, "dir1\\dir2\\dir3"));
                    Console.WriteLine("| " + item + " " + (isDirectory ? "(dir)" : null) + " " + attrib.Size + " bytes");
                }

                #endregion

                #region Read /dir1/dir2/dir3/3.txt

                Console.WriteLine("");
                file = client.Combine("3.txt", "dir1\\dir2\\dir3");
                Console.WriteLine("Reading file 3.txt: " + file);
                stream = new MemoryStream();
                client.Read(file, ref stream);
                if (stream != null)
                {
                    stream.Seek(0, SeekOrigin.Begin);

                    int read = 0;
                    byte[] buf = new byte[4096];

                    while (true)
                    {
                        read = stream.Read(buf, 0, buf.Length);
                        if (read > 0)
                        {
                            byte[] segment = new byte[read];
                            Buffer.BlockCopy(buf, 0, segment, 0, read);
                            Console.WriteLine(Encoding.UTF8.GetString(segment));
                        }
                        else
                        {
                            break;
                        }
                    }
                }

                #endregion

                Console.WriteLine("");
                Console.WriteLine("Finished");
                Console.WriteLine("");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            finally
            {
                if (client != null)
                {
                    if (client.IsMounted)
                    {
                        Console.WriteLine("Unmounting device");
                        client.UnMountDevice();
                    }

                    Console.WriteLine("Disconnecting client");
                    client.Disconnect();
                }
            }
        }
    }
}
```

Output:
```
C:\Code\Misc\NFS-Client\src\Test.Nfs\bin\Debug\net8.0>test.nfs

Initializing client
Mounting device

Listing shares
| /share

Listing root directory
| dir1 (dir) 4096 bytes
| root.txt  10 bytes

Reading file root.txt: \root.txt
Root file


Listing dir1 directory: .\dir1
| dir2 (dir) 4096 bytes
| 1.txt  16 bytes

Reading file 1.txt: .\dir1\1.txt
this is file 1



Listing dir2 directory: .\dir1\dir2
Processing item 2.txt
Processing item dir3

Reading file 2.txt: .\dir1\dir2\2.txt
This is file 2



Listing dir3 directory: .\dir1\dir2\dir3
Processing item 3.txt
| 3.txt  4096 bytes

Reading file 3.txt: .\dir1\dir2\dir3\3.txt
This is file 3



Finished

Unmounting device
Disconnecting client
```

**Comment by jchristn** [comment]
Note that the above works well on Windows machines, but there are issues when adapting the code to run on Linux, specifically when writing or deleting files.  I believe the issue is in the name expected as a parameter to the `NfsClient.Write`, `NfsClient.CreateDirectory`, `Nfs.DeleteFile`, and `Nfs.DeleteDirectory` methods when using Ubuntu.  I'll post an update as I make progress.

**Comment by jchristn** [comment]
Updated the example to include creation of the directory tree, the files, and then subsequent cleanup (deletion of files, deletion of directories).  Works great on Windows, on Ubuntu it immediately threw an exception.

```
namespace Test.Nfs
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.Design.Serialization;
    using System.IO;
    using System.Net;
    using System.Runtime.InteropServices;
    using System.Text;
    using NFSLibrary;
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Protocols.Commons.Exceptions;
    using static System.Runtime.InteropServices.JavaScript.JSType;

    public static class Program
    {
        private static string _Hostname = "192.168.226.132";
        private static NfsClient.NfsVersion _Version = NfsClient.NfsVersion.V3;
        private static string _Share = "/share";

        /*

        /
        |-- root.txt
        |-- dir1
            |-- 1.txt
            |-- dir2
                |-- 2.txt
                |-- dir3
                    |-- 3.txt
                  
         */

        public static void Main(string[] args)
        {
            NfsClient client = null;
            string file = "";
            string folder = "";

            try
            {
                #region Initialize and Mount

                Console.WriteLine("");
                Console.WriteLine("Initializing client");
                client = new NfsClient(_Version);
                client.Connect(IPAddress.Parse(_Hostname));
                Console.WriteLine("Mounting device");
                client.MountDevice(_Share);

                #endregion

                #region List Shares

                Console.WriteLine("");
                Console.WriteLine("Listing shares");
                List<string> exports = client.GetExportedDevices();
                if (exports != null && exports.Count > 0)
                    foreach (var share in exports)
                        Console.WriteLine("| " + share);

                #endregion

                #region Enumerate Root

                Console.WriteLine("");
                Console.WriteLine("Listing root directory");
                foreach (string item in client.GetItemList("."))
                    GetAndDisplayItemAttributes(client, item);

                #endregion

                #region Create /root.txt

                Console.WriteLine("");
                file = PreparedFilename("root.txt");
                Console.WriteLine("Writing file root.txt");
                WriteFile(client, file, "Root file");

                #endregion

                #region Create /dir1

                Console.WriteLine("");
                folder = PreparedDirectoryName("/dir1");
                Console.WriteLine("Creating directory " + folder);
                CreateDirectory(client, folder);

                #endregion

                #region Create /dir1/dir2

                Console.WriteLine("");
                folder = PreparedDirectoryName("/dir1/dir2");
                Console.WriteLine("Creating directory " + folder);
                CreateDirectory(client, folder);

                #endregion

                #region Create /dir1/dir2/dir3

                Console.WriteLine("");
                folder = PreparedDirectoryName("/dir1/dir2/dir3");
                Console.WriteLine("Creating directory " + folder);
                CreateDirectory(client, folder);

                #endregion

                #region Create /dir1/1.txt

                Console.WriteLine("");
                file = PreparedFilename("/dir1/1.txt");
                Console.WriteLine("Creating file " + file);
                WriteFile(client, file, "1");

                #endregion

                #region Create /dir1/dir2/2.txt

                Console.WriteLine("");
                file = PreparedFilename("/dir1/dir2/2.txt");
                Console.WriteLine("Creating file " + file);
                WriteFile(client, file, "2");

                #endregion

                #region Create /dir1/dir2/dir3/3.txt

                Console.WriteLine("");
                file = PreparedFilename("/dir1/dir2/dir3/3.txt");
                Console.WriteLine("Creating file " + file);
                WriteFile(client, file, "3");

                #endregion

                #region Read /root.txt

                Console.WriteLine("");
                file = PreparedFilename("root.txt");
                Console.WriteLine("Reading file root.txt: " + file);
                ReadAndPrintFile(client, file);

                #endregion

                #region Enumerate /dir1

                Console.WriteLine("");
                // folder = client.Combine("dir1", ".");
                folder = PreparedDirectoryName("/dir1/");
                Console.WriteLine("Listing dir1 directory: " + folder);
                foreach (string item in client.GetItemList(folder))
                {
                    string prepared = PreparedFilename(folder + "/" + item);
                    GetAndDisplayItemAttributes(client, prepared);
                }

                #endregion

                #region Read /dir1/1.txt

                Console.WriteLine("");
                file = PreparedFilename("/dir1/1.txt");
                Console.WriteLine("Reading file 1.txt: " + file);
                ReadAndPrintFile(client, file);

                #endregion

                #region Enumerate /dir2

                Console.WriteLine("");
                // folder = client.Combine("dir2", "dir1");
                folder = PreparedDirectoryName("/dir1/dir2/");
                Console.WriteLine("Listing dir2 directory: " + folder);
                foreach (string item in client.GetItemList(folder))
                {
                    string prepared = PreparedFilename(folder + "/" + item);
                    GetAndDisplayItemAttributes(client, prepared);
                }

                #endregion

                #region Read /dir1/dir2/2.txt

                Console.WriteLine("");
                file = PreparedFilename("/dir1/dir2/2.txt");
                Console.WriteLine("Reading file 2.txt: " + file);
                ReadAndPrintFile(client, file);

                #endregion

                #region Enumerate /dir3

                Console.WriteLine("");
                // folder = client.Combine("dir3", "dir1\\dir2");
                folder = PreparedDirectoryName("/dir1/dir2/dir3/");
                Console.WriteLine("Listing dir3 directory: " + folder);
                foreach (string item in client.GetItemList(folder))
                {
                    string prepared = PreparedFilename(folder + "/" + item);
                    GetAndDisplayItemAttributes(client, prepared);
                }

                #endregion

                #region Read /dir1/dir2/dir3/3.txt

                Console.WriteLine("");
                file = PreparedFilename("/dir1/dir2/dir3/3.txt");
                Console.WriteLine("Reading file 3.txt: " + file);
                ReadAndPrintFile(client, file);

                #endregion

                #region Delete /dir1/dir2/dir3/3.txt

                Console.WriteLine("");
                file = PreparedFilename("/dir1/dir2/dir3/3.txt");
                Console.WriteLine("Deleting file: " + file);
                client.DeleteFile(file);

                #endregion

                #region Delete /dir1/dir2/2.txt

                Console.WriteLine("");
                file = PreparedFilename("/dir1/dir2/2.txt");
                Console.WriteLine("Deleting file: " + file);
                client.DeleteFile(file);

                #endregion

                #region Delete /dir1/1.txt

                Console.WriteLine("");
                file = PreparedFilename("/dir1/1.txt");
                Console.WriteLine("Deleting file: " + file);
                client.DeleteFile(file);

                #endregion

                #region Delete /root.txt

                Console.WriteLine("");
                file = PreparedFilename("/root.txt");
                Console.WriteLine("Deleting file: " + file);
                client.DeleteFile(file);

                #endregion

                #region Remove Directory /dir1/dir2/dir3/

                Console.WriteLine("");
                folder = PreparedDirectoryName("/dir1/dir2/dir3");
                Console.WriteLine("Deleting directory: " + folder);
                client.DeleteDirectory(folder);

                #endregion

                #region Remove Direcotry /dir1/dir2/

                Console.WriteLine("");
                folder = PreparedDirectoryName("/dir1/dir2");
                Console.WriteLine("Deleting directory: " + folder);
                client.DeleteDirectory(folder);

                #endregion

                #region Remove Directory /dir1

                Console.WriteLine("");
                folder = PreparedDirectoryName("/dir1");
                Console.WriteLine("Deleting directory: " + folder);
                client.DeleteDirectory(folder);

                #endregion

                Console.WriteLine("");
                Console.WriteLine("Finished");
                Console.WriteLine("");
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            finally
            {
                if (client != null)
                {
                    if (client.IsMounted)
                    {
                        Console.WriteLine("Unmounting device");
                        client.UnMountDevice();
                    }

                    Console.WriteLine("Disconnecting client");
                    client.Disconnect();
                }
            }
        }

        private static void GetAndDisplayItemAttributes(NfsClient client, string item)
        {
            NFSAttributes attrib = client.GetItemAttributes(item);
            if (attrib == null) return;

            bool isDirectory = client.IsDirectory(item);
            Console.WriteLine("| " + item + " " + (isDirectory ? "(dir)" : null) + " " + attrib.Size + " bytes");
        }

        private static void ReadAndPrintFile(NfsClient client, string item)
        {
            Stream stream = new MemoryStream();

            client.Read(item, ref stream);
            if (stream != null)
            {
                stream.Seek(0, SeekOrigin.Begin);

                int read = 0;
                byte[] buf = new byte[4096];

                while (true)
                {
                    read = stream.Read(buf, 0, buf.Length);
                    if (read > 0)
                    {
                        byte[] segment = new byte[read];
                        Buffer.BlockCopy(buf, 0, segment, 0, read);
                        Console.Write(Encoding.UTF8.GetString(segment));
                    }
                    else
                    {
                        break;
                    }
                }
            }

            Console.WriteLine("");

            if (stream != null)
            {
                stream.Close();
                stream.Dispose();
            }
        }

        private static void WriteFile(NfsClient client, string file, string contents)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                stream.Write(Encoding.UTF8.GetBytes(contents));
                stream.Seek(0, SeekOrigin.Begin);
                client.Write(file, stream);
            }
        }

        private static string PreparedFilename(string filename)
        {
            // expect files of the form /path/to/directory/file.txt
            // or without the leading slash

            if (System.String.IsNullOrEmpty(filename)) return null;

            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                filename = filename
                    .Replace("/", "\\")
                    .Replace("\\\\", "\\");

                while (filename.StartsWith("\\")) filename = filename.Substring(1);
                while (filename.EndsWith("\\")) filename = filename.Substring(0, filename.Length - 1);
                filename = ".\\" + filename;
                filename = filename.Replace(".\\.\\", ".\\");
                return filename;
            }
            else
            {
                filename = filename
                    .Replace("/", "\\")
                    .Replace("\\\\", "\\");

                while (filename.StartsWith("\\")) filename = filename.Substring(1);
                while (filename.EndsWith("\\")) filename = filename.Substring(0, filename.Length - 1);
                filename = ".\\" + filename;
                filename = filename.Replace(".\\.\\", ".\\");
                return filename;
            }
        }

        private static string PreparedDirectoryName(string dirname)
        {
            // expect files of the form /path/to/directory/
            // or without the leading or trailing slashes

            if (System.String.IsNullOrEmpty(dirname)) return null;

            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                dirname = dirname
                    .Replace("/", "\\")
                    .Replace("\\\\", "\\");

                while (dirname.StartsWith("\\")) dirname = dirname.Substring(1);
                while (dirname.EndsWith("\\")) dirname = dirname.Substring(0, dirname.Length - 1);
                return ".\\" + dirname;
            }
            else
            {
                dirname = dirname
                    .Replace("/", "\\")
                    .Replace("\\\\", "\\");

                while (dirname.StartsWith("\\")) dirname = dirname.Substring(1);
                while (dirname.EndsWith("\\")) dirname = dirname.Substring(0, dirname.Length - 1);
                return "\\" + dirname;
            }
        }

        private static void CreateDirectory(NfsClient client, string dirname)
        {
            string prepared = PreparedDirectoryName(dirname);
            try
            {
                client.CreateDirectory(prepared);
            }
            catch (NFSIOException)
            {
                Console.WriteLine("Directory already exists");
            }
        }
    }
}
```

On Windows, the output is:
```
Initializing client
Mounting device

Listing shares
| /share

Listing root directory

Writing file root.txt

Creating directory .\dir1

Creating directory .\dir1\dir2

Creating directory .\dir1\dir2\dir3

Creating file .\dir1\1.txt

Creating file .\dir1\dir2\2.txt

Creating file .\dir1\dir2\dir3\3.txt

Reading file root.txt: .\root.txt
Root file

Listing dir1 directory: .\dir1
| .\dir1\dir2 (dir) 4096 bytes
| .\dir1\1.txt  1 bytes

Reading file 1.txt: .\dir1\1.txt
1

Listing dir2 directory: .\dir1\dir2
| .\dir1\dir2\2.txt  1 bytes
| .\dir1\dir2\dir3 (dir) 4096 bytes

Reading file 2.txt: .\dir1\dir2\2.txt
2

Listing dir3 directory: .\dir1\dir2\dir3
| .\dir1\dir2\dir3\3.txt  1 bytes

Reading file 3.txt: .\dir1\dir2\dir3\3.txt
3

Deleting file: .\dir1\dir2\dir3\3.txt

Deleting file: .\dir1\dir2\2.txt

Deleting file: .\dir1\1.txt

Deleting file: .\root.txt

Deleting directory: .\dir1\dir2\dir3

Deleting directory: .\dir1\dir2

Deleting directory: .\dir1

Finished

Unmounting device
Disconnecting client
```

On Ubuntu:
```
Initializing client
Mounting device

Listing shares
| /share

Listing root directory

Writing file root.txt
System.NullReferenceException: Object reference not set to an instance of an object.
   at NFSLibrary.Protocols.V3.NFSv3.Write(String FileFullName, Int64 Offset, Int32 Count, Byte[] Buffer) in /home/joel/Code/NFS2/NFSLibrary/Protocols/V3/NFSv3.cs:line 527
   at NFSLibrary.NfsClient.Write(String destinationFileFullName, Int64 inputOffset, Stream inputStream) in /home/joel/Code/NFS2/NFSLibrary/NFS.cs:line 575
   at NFSLibrary.NfsClient.Write(String destinationFileFullName, Stream inputStream) in /home/joel/Code/NFS2/NFSLibrary/NFS.cs:line 546
   at Test.Nfs.Program.WriteFile(NfsClient client, String file, String contents) in /home/joel/Code/NFS2/Test.Nfs/Program.cs:line 353
   at Test.Nfs.Program.Main(String[] args) in /home/joel/Code/NFS2/Test.Nfs/Program.cs:line 78
Unmounting device
Disconnecting client
```
