### ISSUE TITLE
NFS.cs CorrectPath method doesn't work on Ubuntu 22.04

### ISSUE THREAD

**Issue by jchristn** [SonnyX/NFS-Client#4]
On Windows, the result of `CorrectPath` when called during an `NfsClient.Write` invocation works correctly, but fails on Ubuntu 22.04.

I added a simple `Console.WriteLine` on the output of `CorrectPath` and tested on both Windows and Ubuntu.

Using the example in issue https://github.com/SonnyX/NFS-Client/issues/2

Windows:
```
Initializing client
Mounting device

Listing shares
| /share

Listing root directory

Writing file: .\root.txt
Destination filename: .\root.txt <-----

Creating directory .\dir1

Creating directory .\dir1\dir2

Creating directory .\dir1\dir2\dir3

Writing file: .\dir1\1.txt
Destination filename: .\dir1\1.txt <-----

Writing file: .\dir1\dir2\2.txt
Destination filename: .\dir1\dir2\2.txt <-----

Writing file: .\dir1\dir2\dir3\3.txt
Destination filename: .\dir1\dir2\dir3\3.txt <-----
```

Ubuntu:
```
Initializing client
Mounting device

Listing shares
| /share

Listing root directory

Writing file: root.txt
Destination filename: .\root.txt <-----
System.NullReferenceException: Object reference not set to an instance of an object.
   at NFSLibrary.Protocols.V3.NFSv3.Write(String FileFullName, Int64 Offset, Int32 Count, Byte[] Buffer) in /home/joel/Code/NFS2/NFSLibrary/Protocols/V3/NFSv3.cs:line 527
   at NFSLibrary.NfsClient.Write(String destinationFileFullName, Int64 inputOffset, Stream inputStream) in /home/joel/Code/NFS2/NFSLibrary/NFS.cs:line 576
   at NFSLibrary.NfsClient.Write(String destinationFileFullName, Stream inputStream) in /home/joel/Code/NFS2/NFSLibrary/NFS.cs:line 546
   at Test.Nfs.Program.WriteFile(NfsClient client, String file, String contents) in /home/joel/Code/NFS2/Test.Nfs/Program.cs:line 353
   at Test.Nfs.Program.Main(String[] args) in /home/joel/Code/NFS2/Test.Nfs/Program.cs:line 78
```

**Comment by jchristn** [comment]
This change in `NFS.cs` seems to work for items in the root directory, on Ubuntu 22.04, using `System.Runtime.InteropServices`, but does not (yet) work for items nested in subfolders.
```
        public static string CorrectPath(string pathEntry)
        {
            if (IsNullOrEmpty(pathEntry))
                return pathEntry;

            string[] pathList = pathEntry.Split('\\');

            pathEntry = Join("\\", pathList.Where(item => !IsNullOrEmpty(item)).ToArray());

            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                if (pathEntry.IndexOf('.') != 0)
                {
                    pathEntry = Concat(".\\", pathEntry);
                }
            }
            else
            {
                pathEntry = Concat("\\", pathEntry);
            }

            return pathEntry;
        }
```
